### ISSUE TITLE
Is it possible to save project when closing?

### ISSUE THREAD

**Issue by ttustonic** [WildGums/Orc.ProjectManagement#133] opened 2020-01-21 13:52 UTC
ONLY active OSS contributors OR people who buy me a coffee can ask questions here.  If you don't do either of these things - DO NOT FILE HERE OR I WILL SIMPLY REMOVE YOUR ACCOUNT :)

Give as much details as humanly possible if you want any sort of answer!

Enter Question Below (don't delete this line)

I'm trying to save an  project when closing, but it always times out. I have tried using project watcher and event handler, but it's always the same, it never goes past line 
`using (await asyncLock.LockAsync())`
in `SynchronizeProjectOperationAsync` method in the ProjectManager.

It works fine when I make public and use method `ProjectManager.SyncedSaveAsync` instead of `ProjectManager.SaveAsync`

So, is it possible to save when closing and is there an example of this? 

Thanks, 
Tom

**Comment by GeertvanHorrik** [comment] 2020-01-21 15:06
@mkhomutov , could you answer this one?

**Comment by mkhomutov** [comment] 2020-01-21 20:45
I don't understand the problem.

>I'm trying to save an project when closing, but it always times out.

what do you mean by that? do you mean the application is closing faster than the project is saved?
If so, then you should hold down your application closing progress. Then finish saving and continue closing your application
>So, is it possible to save when closing and is there an example of this?

yes, it is possible. 
please look here https://github.com/WildGums/CsvTextEditor

**Comment by ttustonic** [comment] 2020-01-21 21:07
I mean I want to save project in the `ProjectManager.ProjectClosingAsync` event or in project watcher `OnClosingAsync` method.

It has nothing to do with the application closing. The scenario is this: I have a project loaded in the application. Then I want to load a new project (or create a new one) and save the old one if dirty. I tried something like `CloseBeforeLoadProjectWatcher` and calling `ProjectManager.SaveAsync `in the `OnClosingAsync` but, as I said, it never goes past `asyncLock.LockAsync` line.

I'll look at the Csv text editor to see how it's done.
Thanks,
Tom

**Comment by mkhomutov** [comment] 2020-01-22 05:04
probably you did not use `async` keywords for handling project closing event (or for the overridden `OnClosingAsync()` method in watcher)  and you probably did not use `await` for `ProjectManager.SaveAsync`.

this is actually should work:

```
protected override async Task OnClosingAsync(ProjectCancelEventArgs e)
{
     await _projectManager.SaveAsync();
}
```

in CsvTextEditor look into implementation of `CsvTextEditorIsDirtyProjectWatcher`

**Comment by ttustonic** [comment] 2020-01-22 20:44
Hm, it looks this is closed too early.
Yes, of course I used async/await everywhere.
I also looked at `CsvTextEditorIsDirtyProjectWatcher` and it's the same behavior.
I open a CSV file, make an edit and try to open another file without saving first.
Again, it blocks on the 
`return await _projectManager.SaveAsync(project.Location).ConfigureAwait(false);`
in `SaveProjectChangesService`.

Perhaps it has something to do with `AsyncLock` not being recursive?

**Comment by mkhomutov** [comment] 2020-01-23 04:44
sorry, you're right.
I've managed to reproduce it
will try to find a solution

thanks

**Comment by GeertvanHorrik** [comment] 2020-05-30 07:24
@mkhomutov , what's the status?

**Comment by mkhomutov** [comment] 2020-05-31 04:48
at the bottom of my todo list

**Comment by mkhomutov** [comment] 2020-11-23 19:33
can't reproduce the issue anymore

**Comment by mkhomutov** [comment] 2020-11-23 19:41
sorry, I am still able to reproduce
working on it

**Comment by mkhomutov** [comment] 2020-12-07 06:48
fixed

**Closed by mkhomutov** 2020-12-07 06:48 UTC
